### ISSUE TITLE
Some bugs with the notebooks

### ISSUE THREAD

**Issue by palnabarun** [altair-viz/altair_notebooks#16]
1. Incorrect links to the documentation. For example, in `02-Tutorial.ipynb` between Cell 3 and Cell 4, the `Defining Data` link points to `https://altair-viz.github.io/documentation/data.html`, whereas it should have pointed to `https://altair-viz.github.io/user_guide/data.html`. All such instances occur in `02-Tutorial.ipynb` only.

2. `Import Error` in `01-index.ipynb` as mentioned in #3

**Comment by jakevdp** [comment]
Fixed in #c4d3ea3
