### ISSUE TITLE
Altair plots not rendering when exploring the notebooks from Github

### ISSUE THREAD

**Issue by luisesanmartin** [altair-viz/altair_notebooks#26]
The Altair plots of the notebooks are not being displayed when exploring the notebooks from Github directly. All they show is the number of the code chunk but the output is blank. At first, I thought that it could be a problem of my web browser but I have run into the same problem in Firefox (for Ubuntu and Windows), Chrome (Windows) and Edge (Windows).

The issue might be more related to how Github renders the plots, though, but thanks in advance for taking a look into that.

**Comment by jakevdp** [comment]
Yes, the issue is that charts are displayed using Javascript, and github scrubs all javascript from the display. I'd suggest using http://nbviewer.jupyter.org to view notebooks hosted on github.

**Comment by luisesanmartin** [comment]
Great! That works completely fine.
Closing the issue now. Thank you!

**Comment by Mandar89** [comment]
Thanks a lot! That works completely fine.
