### ISSUE TITLE
Update notebooks for Altair 2.0

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair_notebooks#4]
Most of the contents should work as-is, but it would be nice to add some specifics about selection, maps, layers, etc.

**Comment by Chekos** [comment]
I would love to help with this. I have never contributed to any open source project but I really like altair. I was actually going to start a little series of simple and quick altair examples myself [like this](https://github.com/Chekos/blog-posts/tree/master/altair%20%2B%20ipywidgets) but I'd rather contribute directly to the docs if possible. 

I just don't know where or how to start really.

**Comment by jakevdp** [comment]
Done in master
